sudo: false

language: node_js
node_js:
- stable

notifications:
  email:
    on_success: never
    on_failure: change

git:
  depth: 2

cache:
  yarn: true

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

script: skip

after_success:
  - scripts/after-success.sh || exit $?

before_deploy:
  - yarn build-storybook
  - yarn global add makeshift && makeshift -r registry.npmjs.org

deploy:
  - provider: npm
    email: v7rulnik@gmail.com
    skip_cleanup: true
    api_key: $NPM_TOKEN
    on:
      tags: true
      branch: master
      repo: kupibilet-frontend/ui

  - provider: pages
    local_dir: storybook-static
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    on:
      branch: master
      tags: false

after_script:
  - echo $TRAVIS_BRANCH
  - echo $TRAVIS_PULL_REQUEST
  - echo ${#TRAVIS_PULL_REQUEST}
    # the command terminates with an error code, even if it does not find vulnerabilities of the specified level.
    # For the behavior we need, we set a condition under which the command terminates with an error code
    # only if there is a vulnerability of this level in its output
    # https://github.com/yarnpkg/yarn/issues/7260
  - bash -c 'output=`yarn audit --level=high`; ret_code=$?; echo "$output"; [[ $output =~ "high" ]]
    && exit $ret_code || exit 0'
  - '[ $TRAVIS_PULL_REQUEST != "false" ] && exit 0 || [[ $TRAVIS_BRANCH =~ "master" ]] && yarn run
  snyk'