language: node_js
node_js:
- stable

before_install:
  - yarn global add makeshift && makeshift

script:
  - npm run build-storybook

deploy:
  - provider: npm
    email: v7rulnik@gmail.com
    skip_cleanup: true
    api_key: $NPM_TOKEN
    on:
      branch: master
      tags: true
      repo: kupibilet-frontend/ui
  -
    provider: pages
    local_dir: storybook-static
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    on:
      branch: master
