language: node_js
node_js:
- stable
git:
  depth: 2

script:
  - yarn test

before_deploy:
  - yarn build-storybook
  - yarn global add makeshift && makeshift -r registry.npmjs.org

deploy:
  - provider: npm
    email: v7rulnik@gmail.com
    skip_cleanup: true
    api_key: $NPM_TOKEN
    on:
      branch: master
      tags: true
      repo: kupibilet-frontend/ui

  - provider: pages
    local_dir: storybook-static
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    on:
      branch: master
