// flow-typed signature: c882fdb2796e6b7681da376ba6d697a5
// flow-typed version: <<STUB>>/eslint-config-kupibilet_v^8.2.3/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-kupibilet'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-kupibilet' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'eslint-config-kupibilet/index' {
  declare module.exports: $Exports<'eslint-config-kupibilet'>;
}
declare module 'eslint-config-kupibilet/index.js' {
  declare module.exports: $Exports<'eslint-config-kupibilet'>;
}
