// flow-typed signature: 15965aa713c65e49f13ab696ede1ca17
// flow-typed version: <<STUB>>/move-binaries-to-bin_v~1.0.1/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'move-binaries-to-bin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'move-binaries-to-bin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'move-binaries-to-bin/bin/move-bin' {
  declare module.exports: any;
}

// Filename aliases
declare module 'move-binaries-to-bin/bin/move-bin.js' {
  declare module.exports: $Exports<'move-binaries-to-bin/bin/move-bin'>;
}
declare module 'move-binaries-to-bin/index' {
  declare module.exports: $Exports<'move-binaries-to-bin'>;
}
declare module 'move-binaries-to-bin/index.js' {
  declare module.exports: $Exports<'move-binaries-to-bin'>;
}
