// flow-typed signature: b801fb8b9dbaea37d05848e028d8f906
// flow-typed version: <<STUB>>/rc-collapse_v~1.7.0/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rc-collapse'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rc-collapse' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rc-collapse/lib/Collapse' {
  declare module.exports: any;
}

declare module 'rc-collapse/lib/index' {
  declare module.exports: any;
}

declare module 'rc-collapse/lib/openAnimationFactory' {
  declare module.exports: any;
}

declare module 'rc-collapse/lib/Panel' {
  declare module.exports: any;
}

declare module 'rc-collapse/lib/PanelContent' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rc-collapse/lib/Collapse.js' {
  declare module.exports: $Exports<'rc-collapse/lib/Collapse'>;
}
declare module 'rc-collapse/lib/index.js' {
  declare module.exports: $Exports<'rc-collapse/lib/index'>;
}
declare module 'rc-collapse/lib/openAnimationFactory.js' {
  declare module.exports: $Exports<'rc-collapse/lib/openAnimationFactory'>;
}
declare module 'rc-collapse/lib/Panel.js' {
  declare module.exports: $Exports<'rc-collapse/lib/Panel'>;
}
declare module 'rc-collapse/lib/PanelContent.js' {
  declare module.exports: $Exports<'rc-collapse/lib/PanelContent'>;
}
