// flow-typed signature: 6a7b72fcb5824f09ad948da9c2a65200
// flow-typed version: <<STUB>>/rc-tabs_v^7.5.0/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rc-tabs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rc-tabs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rc-tabs/es/index' {
  declare module.exports: any;
}

declare module 'rc-tabs/es/InkTabBar' {
  declare module.exports: any;
}

declare module 'rc-tabs/es/InkTabBarMixin' {
  declare module.exports: any;
}

declare module 'rc-tabs/es/KeyCode' {
  declare module.exports: any;
}

declare module 'rc-tabs/es/ScrollableInkTabBar' {
  declare module.exports: any;
}

declare module 'rc-tabs/es/ScrollableTabBar' {
  declare module.exports: any;
}

declare module 'rc-tabs/es/ScrollableTabBarMixin' {
  declare module.exports: any;
}

declare module 'rc-tabs/es/SwipeableInkTabBar' {
  declare module.exports: any;
}

declare module 'rc-tabs/es/SwipeableTabBarMixin' {
  declare module.exports: any;
}

declare module 'rc-tabs/es/SwipeableTabContent' {
  declare module.exports: any;
}

declare module 'rc-tabs/es/TabBar' {
  declare module.exports: any;
}

declare module 'rc-tabs/es/TabBarMixin' {
  declare module.exports: any;
}

declare module 'rc-tabs/es/TabContent' {
  declare module.exports: any;
}

declare module 'rc-tabs/es/TabPane' {
  declare module.exports: any;
}

declare module 'rc-tabs/es/Tabs' {
  declare module.exports: any;
}

declare module 'rc-tabs/es/utils' {
  declare module.exports: any;
}

declare module 'rc-tabs/lib/index' {
  declare module.exports: any;
}

declare module 'rc-tabs/lib/InkTabBar' {
  declare module.exports: any;
}

declare module 'rc-tabs/lib/InkTabBarMixin' {
  declare module.exports: any;
}

declare module 'rc-tabs/lib/KeyCode' {
  declare module.exports: any;
}

declare module 'rc-tabs/lib/ScrollableInkTabBar' {
  declare module.exports: any;
}

declare module 'rc-tabs/lib/ScrollableTabBar' {
  declare module.exports: any;
}

declare module 'rc-tabs/lib/ScrollableTabBarMixin' {
  declare module.exports: any;
}

declare module 'rc-tabs/lib/SwipeableInkTabBar' {
  declare module.exports: any;
}

declare module 'rc-tabs/lib/SwipeableTabBarMixin' {
  declare module.exports: any;
}

declare module 'rc-tabs/lib/SwipeableTabContent' {
  declare module.exports: any;
}

declare module 'rc-tabs/lib/TabBar' {
  declare module.exports: any;
}

declare module 'rc-tabs/lib/TabBarMixin' {
  declare module.exports: any;
}

declare module 'rc-tabs/lib/TabContent' {
  declare module.exports: any;
}

declare module 'rc-tabs/lib/TabPane' {
  declare module.exports: any;
}

declare module 'rc-tabs/lib/Tabs' {
  declare module.exports: any;
}

declare module 'rc-tabs/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rc-tabs/es/index.js' {
  declare module.exports: $Exports<'rc-tabs/es/index'>;
}
declare module 'rc-tabs/es/InkTabBar.js' {
  declare module.exports: $Exports<'rc-tabs/es/InkTabBar'>;
}
declare module 'rc-tabs/es/InkTabBarMixin.js' {
  declare module.exports: $Exports<'rc-tabs/es/InkTabBarMixin'>;
}
declare module 'rc-tabs/es/KeyCode.js' {
  declare module.exports: $Exports<'rc-tabs/es/KeyCode'>;
}
declare module 'rc-tabs/es/ScrollableInkTabBar.js' {
  declare module.exports: $Exports<'rc-tabs/es/ScrollableInkTabBar'>;
}
declare module 'rc-tabs/es/ScrollableTabBar.js' {
  declare module.exports: $Exports<'rc-tabs/es/ScrollableTabBar'>;
}
declare module 'rc-tabs/es/ScrollableTabBarMixin.js' {
  declare module.exports: $Exports<'rc-tabs/es/ScrollableTabBarMixin'>;
}
declare module 'rc-tabs/es/SwipeableInkTabBar.js' {
  declare module.exports: $Exports<'rc-tabs/es/SwipeableInkTabBar'>;
}
declare module 'rc-tabs/es/SwipeableTabBarMixin.js' {
  declare module.exports: $Exports<'rc-tabs/es/SwipeableTabBarMixin'>;
}
declare module 'rc-tabs/es/SwipeableTabContent.js' {
  declare module.exports: $Exports<'rc-tabs/es/SwipeableTabContent'>;
}
declare module 'rc-tabs/es/TabBar.js' {
  declare module.exports: $Exports<'rc-tabs/es/TabBar'>;
}
declare module 'rc-tabs/es/TabBarMixin.js' {
  declare module.exports: $Exports<'rc-tabs/es/TabBarMixin'>;
}
declare module 'rc-tabs/es/TabContent.js' {
  declare module.exports: $Exports<'rc-tabs/es/TabContent'>;
}
declare module 'rc-tabs/es/TabPane.js' {
  declare module.exports: $Exports<'rc-tabs/es/TabPane'>;
}
declare module 'rc-tabs/es/Tabs.js' {
  declare module.exports: $Exports<'rc-tabs/es/Tabs'>;
}
declare module 'rc-tabs/es/utils.js' {
  declare module.exports: $Exports<'rc-tabs/es/utils'>;
}
declare module 'rc-tabs/lib/index.js' {
  declare module.exports: $Exports<'rc-tabs/lib/index'>;
}
declare module 'rc-tabs/lib/InkTabBar.js' {
  declare module.exports: $Exports<'rc-tabs/lib/InkTabBar'>;
}
declare module 'rc-tabs/lib/InkTabBarMixin.js' {
  declare module.exports: $Exports<'rc-tabs/lib/InkTabBarMixin'>;
}
declare module 'rc-tabs/lib/KeyCode.js' {
  declare module.exports: $Exports<'rc-tabs/lib/KeyCode'>;
}
declare module 'rc-tabs/lib/ScrollableInkTabBar.js' {
  declare module.exports: $Exports<'rc-tabs/lib/ScrollableInkTabBar'>;
}
declare module 'rc-tabs/lib/ScrollableTabBar.js' {
  declare module.exports: $Exports<'rc-tabs/lib/ScrollableTabBar'>;
}
declare module 'rc-tabs/lib/ScrollableTabBarMixin.js' {
  declare module.exports: $Exports<'rc-tabs/lib/ScrollableTabBarMixin'>;
}
declare module 'rc-tabs/lib/SwipeableInkTabBar.js' {
  declare module.exports: $Exports<'rc-tabs/lib/SwipeableInkTabBar'>;
}
declare module 'rc-tabs/lib/SwipeableTabBarMixin.js' {
  declare module.exports: $Exports<'rc-tabs/lib/SwipeableTabBarMixin'>;
}
declare module 'rc-tabs/lib/SwipeableTabContent.js' {
  declare module.exports: $Exports<'rc-tabs/lib/SwipeableTabContent'>;
}
declare module 'rc-tabs/lib/TabBar.js' {
  declare module.exports: $Exports<'rc-tabs/lib/TabBar'>;
}
declare module 'rc-tabs/lib/TabBarMixin.js' {
  declare module.exports: $Exports<'rc-tabs/lib/TabBarMixin'>;
}
declare module 'rc-tabs/lib/TabContent.js' {
  declare module.exports: $Exports<'rc-tabs/lib/TabContent'>;
}
declare module 'rc-tabs/lib/TabPane.js' {
  declare module.exports: $Exports<'rc-tabs/lib/TabPane'>;
}
declare module 'rc-tabs/lib/Tabs.js' {
  declare module.exports: $Exports<'rc-tabs/lib/Tabs'>;
}
declare module 'rc-tabs/lib/utils.js' {
  declare module.exports: $Exports<'rc-tabs/lib/utils'>;
}
