// flow-typed signature: a7b397631e2a9268673bdd55cc637485
// flow-typed version: <<STUB>>/react-onclickoutside_v^5.11.1/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-onclickoutside'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-onclickoutside' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-onclickoutside/index' {
  declare module.exports: $Exports<'react-onclickoutside'>;
}
declare module 'react-onclickoutside/index.js' {
  declare module.exports: $Exports<'react-onclickoutside'>;
}
