// flow-typed signature: 522a3d64be18d96d9e2fc2ac3a29c267
// flow-typed version: <<STUB>>/section-iterator_v^2.0.0/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'section-iterator'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'section-iterator' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'section-iterator/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'section-iterator/dist/index.js' {
  declare module.exports: $Exports<'section-iterator/dist/index'>;
}
