// flow-typed signature: bd500ee0cfb0d702c2089c47003cbb39
// flow-typed version: <<STUB>>/stylelint-config-kupibilet_v^3.1.2/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stylelint-config-kupibilet'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'stylelint-config-kupibilet' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'stylelint-config-kupibilet/index' {
  declare module.exports: $Exports<'stylelint-config-kupibilet'>;
}
declare module 'stylelint-config-kupibilet/index.js' {
  declare module.exports: $Exports<'stylelint-config-kupibilet'>;
}
