// flow-typed signature: bfc5acdb3773f0a63ce44aa5c0d5d32e
// flow-typed version: <<STUB>>/@kupibilet/icons_v~3.3.0/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@kupibilet/icons'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@kupibilet/icons' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@kupibilet/icons/dist/sprite' {
  declare module.exports: any;
}

// Filename aliases
declare module '@kupibilet/icons/dist/sprite.js' {
  declare module.exports: $Exports<'@kupibilet/icons/dist/sprite'>;
}
