// flow-typed signature: 5a5e5c4bf534990df7625ce45345bd17
// flow-typed version: <<STUB>>/@kadira/react-storybook-decorator-centered_v~1.1.2/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@kadira/react-storybook-decorator-centered'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@kadira/react-storybook-decorator-centered' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@kadira/react-storybook-decorator-centered/build/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@kadira/react-storybook-decorator-centered/build/index.js' {
  declare module.exports: $Exports<'@kadira/react-storybook-decorator-centered/build/index'>;
}
declare module '@kadira/react-storybook-decorator-centered/index' {
  declare module.exports: $Exports<'@kadira/react-storybook-decorator-centered'>;
}
declare module '@kadira/react-storybook-decorator-centered/index.js' {
  declare module.exports: $Exports<'@kadira/react-storybook-decorator-centered'>;
}
