/* eslint quote-props: 0 */

/*
 * WARNING!
 *
 * This collection should be used ONLY to add airline name for color in Storybook
 *
 */

const AIRLINE_CODE_TO_NAME_MAP = {
  '81': 'Airtuerk',
  'A9': 'Georgian Airways',
  'A0': 'Avian Lineas Aereas',
  'AU': 'Austral Lineas Aerea',
  'B6': 'JetBlue',
  'AZ': 'Alitalia',
  'AL': 'Skyway Airlines',
  'AJ': 'Aerocontractors',
  'BV': 'Blue Panorama Airlines',
  'C9': 'Cirrus Airlines',
  'C6': 'Canjet Airlines',
  'BU': 'SAS Norway',
  'C5': 'CommutAir',
  'BQ': 'Aeromar Airlines',
  'BM': 'Airbee',
  'D8': 'Norwegian Air International',
  'CV': 'Air Chatham',
  'D4': 'Alidaunia',
  'MQ': 'American Eagle Airlines',
  'O8': 'Oasis',
  'O2': 'Jet Air',
  'OM': 'MIAT',
  'OL': 'OLT Ostfriesische Luftransport',
  'P5': 'Wingo',
  'PN': 'China West Air',
  'PH': 'Polynesian Airlines',
  'HN': 'Heavylift Cargo Airlines',
  'HR': 'Hahn Air',
  'HQ': 'Harmony Airways',
  'XE': 'Express Jet Airlines',
  'WO': 'World Airways',
  'X5': 'Afrique Airlines',
  'WI': 'Tradewinds Airlines',
  'WJ': 'Air Labrador',
  'WK': 'Edelweiss Air',
  'VZ': 'My TravelLite',
  'RP': 'Chautauqua Airlines',
  'S0': 'Slok Air',
  'QW': 'Blue Wings',
  'R9': 'Camai Air',
  'QT': 'Regional Pacific Airlines',
  'QA': 'Aero Caribe',
  'Q8': 'Trans Air Congo',
  'PP': 'Jet Aviation Business Jets',
  'U3': 'Avies LTD',
  'T7': 'Twin Jet',
  'SS': 'Corsair',
  'T9': 'Trans Meridian Airlines',
  'SC': 'Shandong Airlines',
  'SE': 'XL Airways France',
  'SL': 'Thai Lion Air',
  'T2': 'Nakina Air',
  '3Z': 'Everts Air',
  'RW': 'RAS Fluggesellschaft',
  'RY': 'Royal Wings',
  'ZA': 'Astair',
  'ZP': 'ZP',
  'ZW': 'Air Wisconsin',
  'ZR': 'Alexandria Airlines',
  'YL': 'Air Bissau',
  'YJ': 'AMC Airlines',
  'Z6': 'Dnieproavia',
  'YS': 'Regional CAE',
  'Z4': 'Zoom Airlines',
  'YR': 'Scenic Airlines',
  '3A': 'Alliance Airlines',
  '3B': 'Job Air',
  '2Y': 'Air Andaman',
  '2Q': 'Avitrans Nordi',
  '2F': 'Frontier Flying Service',
  '0Y': 'FlyYeti',
  '7A': 'Air Next',
  '7S': 'Artic Transportation Services',
  '5W': 'Astraeus',
  '5Z': 'Bismillah Airlines',
  '4T': 'Belair',
  '5D': 'Aeromexico Connect',
  '5F': 'Fly One',
  '5Q': 'Best Air',
  '5O': 'ASL Airlines France',
  '3U': 'Sichuan Airlines',
  'E5': 'Air Arabia Egypt',
  'AC': 'Air Canada',
  'AF': 'Air France',
  'WN': 'Southwest Airlines',
  'GR': 'Aurigny Air',
  'BE': 'Flybe',
  'MT': 'Thomas Cook Airlines UK',
  'F9': 'Frontier Airlines',
  'ST': 'Germania',
  'OI': 'Hinterland Aviation',
  '3L': 'Intersky',
  'TF': 'Braathens Regional Aviation',
  'JE': 'Mango',
  'ZB': 'Monarch Airlines',
  'NO': 'Neos',
  'FR': 'RyanAir',
  'TZ': 'Scoot',
  'SY': 'Sun Country Airlines',
  'X3': 'TUI fly Germany',
  'VX': 'Virgin America',
  'V7': 'Volotea',
  'WU': 'Wizz Air Ukraine',
  '8S': 'Turbojet',
  'V0': 'Conviasa',
  'T4': 'Trip Linhas Aereas',
  '8D': 'Servant Air',
  'WL': 'Aeroperlas',
  'X9': 'Avion Express',
  'S3': 'Santa Barbara Airlines ',
  'WZ': 'Red Wings',
  'T5': 'Turkmenistan Airlines',
  'UR': 'Uganda Airlines',
  'MA': 'Malev Hungarian Airlines',
  'QH': 'Kyrgystan',
  '6W': 'Саратовские авиалинии',
  'I5': 'Air Asia',
  'GV': 'Grant Aviation',
  '4G': 'Gazpromavia',
  'DJ': 'Virgin Australia',
  '3F': 'Pacific Airways',
  '4L': 'Georgian International Airline',
  '4Q': 'Safi Airways',
  '5H': 'Five Fourty Aviation',
  '5P': 'SkyEurope Airlines Hungary',
  '5U': 'Transportes Aereos Guatemaltecos',
  '6F': 'Aerotrans Airlines',
  '6K': 'Asian Spirit',
  '6L': 'Aklak Air',
  '6Q': 'Slovak Airlines',
  '7I': 'Insel Air',
  '7N': 'PAWA Dominicana',
  'AI': 'Air India',
  'BB': 'Seaborne Airlines',
  'BC': 'Skymark Airlines',
  'BD': 'BMI',
  'BH': 'Hawkair',
  'BI': 'Royal Brunei',
  'BL': 'Jetstar Pacific',
  'BS': 'British International',
  'BW': 'Caribbean Airlines',
  'BX': 'Air Busan',
  'CA': 'Air China',
  'CF': 'City Airline',
  'CI': 'China Airlines',
  'CX': 'Cathay Pacific',
  'D3': 'Daallo Airlines',
  'D6': 'Interair South Africa',
  'DG': 'Cebgo',
  'DT': 'TAAG Angola',
  'DY': 'Norwegian Air',
  'DZ': 'Donghai',
  'МИ': 'FSUAE KMV',
  'HZ': 'Aurora',
  'ФР': 'Center South',
  'S7': 'S7 Airlines',
  'GF': 'Gulf Air',
  'GZ': 'Air Rarotonga',
  'HS': 'Svenska Direktflyg',
  'IB': 'Iberia',
  'IE': 'Solomon Airlines',
  'IF': 'Islas Airways',
  'Q4': 'Swazi Express Airways',
  'Q5': 'Forty Mile Air',
  'QS': 'Smartwings',
  'R6': 'DOT LT',
  'RE': 'Stobart Air',
  'RV': 'Caspian Airlines',
  'RX': 'Regent Airways',
  'S4': 'Azores Airlines',
  'S5': 'Shuttle America',
  'S6': 'Salmon Air',
  'SJ': 'Sriwijaya Air',
  'SV': 'Saudi Arabian Airlines',
  'SZ': 'Somon Air',
  'TG': 'Thai Airways',
  'TI': 'Tailwind Airlines',
  'TP': 'TAP Portugal',
  'TT': 'Tigerair Australia',
  'TY': 'Air Caledonie',
  'U4': 'PMT Air',
  'U7': 'Air Uganda',
  'UB': 'Myanma Airways',
  'UL': 'SriLankan Airlines',
  'UM': 'Air Zimbabwe',
  'IS': 'Island Airlines of Nantucket',
  'IT': 'Tigerair Taiwan',
  'IY': 'Yemenia Yemen Airways',
  'IZ': 'Arkia Israeli Airlines',
  'J3': 'Northwestern Air',
  'JK': 'Spanair',
  'JL': 'Japan Airlines',
  'JM': 'Jambojet',
  'JR': 'Aero California',
  'JU': 'Air Serbia',
  'K3': 'Taquan Air',
  'KA': 'Hong Kong Dragon',
  'KG': 'Aerogaviota',
  'KL': 'KLM',
  'KM': 'Air Malta',
  'KO': 'Комиавиатранс',
  'KU': 'Kuwait Airways',
  'KX': 'Cayman Airways',
  'LI': 'Liat',
  'LN': 'Libyan Airlines',
  'LP': 'Lan Peru ',
  'LR': 'Lacsa',
  'M7': 'Marsland Aviation',
  'MF': 'Xiamen Airlines',
  'MJ': 'Myway Airlines',
  'MK': 'Air Mauritius',
  'MS': 'Egyptair',
  'MY': 'Maya Island Air',
  'NF': 'Air Vanuatu',
  'NX': 'Air Macau',
  'NY': 'Air Iceland',
  'NZ': 'Air New Zealand',
  'OC': 'Oriental Air Bridge',
  'P0': 'Proflight Zambia',
  'P8': 'P.L.A.S.',
  'P9': 'Peruvian Airlines',
  'FD': 'Thai AirAsia',
  'G3': 'Gol Transportes Aereos',
  'G8': 'Go Air',
  '2G': 'Angara Airlines',
  '2Z': 'TTA',
  'TR': 'Scoot',
  'RJ': 'Royal Jordanian',
  'KF': 'Blue1',
  'OZ': 'Asiana Airlines',
  'WH': 'Westair Benin',
  'ШС': 'ООО АК ПАНХ',
  'EL': 'Ellinair',
  'ZM': 'Air Manas',
  'БВ': 'Airport Bratsk',
  'АЯ': 'Air Service CO LTD',
  'OG': 'Air Onix',
  '3G': 'Gambia Bird Airlines',
  'РД': 'ИрАэро',
  'ZG': 'Грозный-Авиа',
  'GH': 'Глобус',
  'ИК': 'Ангара',
  'ТЫ': 'Tulpar Air',
  'OD': 'Malindo Airways',
  '01': 'Buta Airways',
  'КФ': 'Tuva-avia',
  'EA': 'European Air Express',
  'E7': 'Fly European',
  'DW': 'Aero-Charter',
  'DX': 'DAT',
  'DM': 'Sterling Blue',
  'DN': 'Norwegian Air Argentina',
  'EV': 'Atlantic Southeast Airlines',
  'EZ': 'Sun Air of Scandinavia',
  'FN': 'Fastjet',
  'FL': 'Airtran Airways ',
  'FI': 'Icelandair',
  'FH': 'Freebird Airlines',
  'HG': 'Niki ',
  'HD': 'Air Do',
  'GW': 'Kuban Airline',
  'GX': 'JetX',
  'H6': 'Hageland Aviation',
  'GT': 'GB Airways',
  'GM': 'Germania Flug',
  'GI': 'Itek Air',
  'AT': 'Royal Air Maroc',
  'AY': 'Finnair',
  'AH': 'Air Algerie',
  'C3': 'Contact Air',
  'BT': 'Air Baltic',
  'CB': 'ScotAirways',
  'BZ': 'Bluebird Airways',
  'C0': 'Centralwings',
  'BJ': 'Nouvelair Tunisie',
  'CT': 'Alitalia City Liner ',
  'D5': 'Dauair',
  'CJ': 'BA City Flyer',
  'D2': 'Severstal',
  'CP': 'Compass Airlines',
  'LV': 'Level',
  'LU': 'Lan Express',
  'LZ': 'Belle Air',
  'LX': 'Swiss',
  'LO': 'LOT Polish Airlines',
  'LQ': 'Lanmei Airlines',
  'MV': 'Armenian International Airways',
  'MP': 'Martinair',
  'N2': 'Dagestan Airlines',
  'NQ': 'Air Japan',
  'OX': 'Orient',
  'OY': 'Andes Lineas Aeras',
  'Q0': 'Quebecair Express',
  'I7': 'Paramount Airways',
  'I9': 'Air Italy',
  'IJ': 'Great Wall Airlines',
  'J7': 'Centre-Avia Airlines',
  'IW': 'Wings Air',
  'JD': 'Beijing Capital Airlines',
  'JP': 'Adria Airways',
  'VQ': 'Vintage Props &amp;',
  'VI': 'Vieques Air Link',
  'XP': 'Casino Express Airlines',
  'XW': 'NokScoot',
  'XK': 'Air Corsica',
  'ZX': 'Zoom Airlines UK',
  'XZ': 'South African Express',
  'YH': 'West Caribbean Airways',
  'YE': 'Yanair',
  'YD': 'Mauritania Airways',
  'YW': 'Air Nostrum',
  '2U': 'Sun d\'OR',
  '3Q': 'Carib Aviation',
  '3E': 'Air Choice One',
  '2E': 'Smokey Bay Air',
  '7E': 'Panagra Airways ',
  '7D': 'Donbassaero',
  '7Q': 'Tibesti AirLibya',
  '7T': 'Trenitalia S.P.A',
  '4W': 'Warbelows Air Ventures',
  '5B': 'Euro- Asia Air',
  '5K': 'Odessa Airlines',
  '5S': 'Servicios Aereos Profesionales',
  '5T': 'Canadian North',
  '3X': 'Japan Air',
  '3Y': 'Uniways',
  '4A': 'Royal Bengal Airlines',
  '4P': 'Viking Airlines',
  '9Q': 'PB Air Company',
  '9N': 'Tropic Air',
  '9D': 'Toumai Air Tchad',
  'AB': 'Air Berlin',
  'AP': 'AirOne',
  'G4': 'Allegiant Air',
  '0B': 'Blue Air',
  'BA': 'British Airways',
  'DE': 'Condor',
  'NM': 'Manx2',
  'XC': 'Corendon Airlines',
  'KS': 'Peninsula Airways',
  '7K': 'Когалымавиа',
  'WR': 'Aviaprad',
  'UN': 'Transaero',
  'CQ': 'Sunshine Express',
  '2P': 'Airphil Express',
  '4H': 'United Airways Bangladesh',
  '4K': 'Kenn Borek Air ',
  '4Y': 'Yute Air Alaska',
  '5L': 'Aerosur',
  '6C': 'Cape Smythe Air',
  '6E': 'Indigo Air',
  '8U': 'Afriqiyah Airways',
  '9E': 'Nortwest Airlink',
  '9H': 'Dutch Antilles Express',
  'A3': 'Aegean Airlines',
  'A4': 'Azimut',
  'AE': 'Mandarin Airlines',
  'AM': 'Aeromexico',
  'AS': 'Alaska Airlines',
  'AX': 'Trans States',
  'B7': 'Uni Air',
  'B9': 'Iran Air Tours',
  'BF': 'French Bee',
  'BG': 'Biman Bangladesh',
  'BP': 'Air Botswana',
  'CZ': 'China Southern',
  'DH': 'Independence AIr',
  'DL': 'Delta',
  'T6': '1Time ',
  '3P': 'Tiara Air Aruba',
  'FS': 'Itali Airlines',
  'ZF': 'Azur Air',
  'ЮВ': 'ЮВТ Аэро',
  'GE': 'TransAsia Airways',
  'GQ': 'Sky express',
  'GU': 'Aviateca',
  'H2': 'Sky Airline',
  'H4': 'Heli Securite',
  'HA': 'Hawaiian Airlines',
  'SI': 'Blue Islands',
  'SP': 'SATA Air Acores',
  'T3': 'Eastern Airways ',
  'MN': 'Kulula air',
  'MZ': 'Saereo S.A',
  'N6': 'Nuevo Continente ',
  'N7': 'Nordic Regional Airlines',
  'N9': 'Niger Air',
  'NH': 'All Nippon Airways',
  'NL': 'Shaheen Air',
  'NS': 'Northeastern Airlines',
  'ON': 'Our Airline',
  'PU': 'Pluna',
  'EB': 'Wamos Air',
  'XL': 'Lan Ecuador',
  'XU': 'African Express Airways',
  'Z2': 'Bravo Air Congo',
  'ZJ': 'Zambezi Airlines',
  'ZK': 'Great Lakes Airlines',
  'ZL': 'Regional Express',
  'ZO': 'Central Air Transport Services',
  'ZY': 'Ada Air',
  '7L': 'Aerocaribbean',
  'AK': 'AirAsia',
  'KQ': 'Kenya Airways',
  'OV': 'Estonian Air ',
  '6G': 'Gulfstream',
  '9M': 'Central Mountain Air',
  'UF': 'Ukrainian Mediterranean',
  'SO': 'Salsa D\'Haiti',
  'O9': 'Nova Airways',
  'VR': 'Cabo Verde Airlines',
  'JJ': 'TAM',
  'R3': 'Yakutia',
  'CG': 'Airlines of Papua New Guinea',
  'ПМ': 'Pamir Airways',
  'KJ': 'British Mediterranean Airways',
  'R7': 'Aserca Airlines',
  'SU': 'Aeroflot',
  '7V': 'Pelican Air',
  'TN': 'Air Tahiti Nui',
  'FG': 'Ariana Afghan Airlines',
  'YT': 'Air Togo',
  'W2': 'FLEX FLIGHT APS',
  'КБ': 'Костромское авиапредприятие',
  'СЛ': 'ООО Сибирская Легкая Авиация',
  'AD': 'Azul Linhas Aereas Brasileiras',
  '2Ы': 'Местные Авиалинии 2',
  'MR': 'Mongolian Airlines',
  'ВГ': 'АО Вологодское АП',
  'БЮ': 'AC Buryat Airlines',
  'НФ': 'Utair Helicopter Service',
  'KV': 'Asian Express Airlines',
  'Y7': 'NordStar',
  'ЮГ': 'ООО \'Пионер - региональные авиалинии\'',
  'АП': 'Амур',
  'ДЕ': 'АО «Камчатское авиационное предприятие»',
  'EC': 'OpenSkies',
  'EX': 'Air Santo Domingo',
  'EN': 'Air Dolomiti',
  'EF': 'Far Eastern Air',
  'FZ': 'Fly Dubai',
  'FW': 'Ibex Airlines',
  'G5': 'China Express Airlines',
  'FK': 'Keewatin Air',
  'HE': 'LGW',
  'HB': 'Homer Air',
  'H9': 'Pegasus',
  'GS': 'Tianjin Airlines',
  'GP': 'APG Airlines',
  'A6': 'Air Alps',
  'A5': 'HOP!',
  'A8': 'Benin Golf Air',
  'C2': 'Ceiba',
  'CS': 'Continental Micronesia',
  'DC': 'Braathens Regional Airways',
  'DB': 'Brit Air',
  'CE': 'Nationwide Air',
  'YIN': 'Yining Arpt',
  'CD': 'Alliance Air',
  'CN': 'Grand China Air',
  'CL': 'Lufthansa CityLine',
  'M5': 'Kenmore Air',
  'M0': 'Aero Mongolia',
  'M4': 'Aviompex',
  'M3': 'North Flying',
  'M2': 'Mahfooz Aviation',
  'ME': 'Middle East Airlines',
  'ML': 'African Transport',
  'MD': 'Air Madagascar',
  'NW': 'Northwest Airlines',
  'OH': 'Comair',
  'OA': 'Olympic Air',
  'OU': 'Croatia Airlines',
  'PJ': 'Air Saint-Pierre',
  'HO': 'Juneyao Airlines',
  'HU': 'Hainan Airlines',
  'J0': 'Jetlink Express',
  'IP': 'Atyrau Airways',
  'IQ': 'Qazaq Air',
  'IV': 'Wind Jet',
  'JF': 'L A B Flying Service',
  'JI': 'San Juan Aviation',
  'JY': 'InterCaribbean Airways',
  'K4': 'Kronflyg',
  'L4': 'Air Liaison',
  'L5': 'Helikopter Service',
  'LJ': 'Jin Air',
  'LG': 'Luxair',
  'LF': 'FlyNordic',
  'W3': 'Arik Air',
  'VO': 'Tyrolean Airways',
  'UP': 'Bahamasair',
  'UA': 'United Airlines',
  'UD': 'Hex Air',
  'U5': 'USA 3000 Airlines',
  'U8': 'Armavia',
  'Y3': 'Driessen',
  'XT': 'Skystar Airways',
  'XN': 'Air Nepal',
  'Y0': 'Yellow Air Taxi',
  'XF': 'Vladivostok Air',
  'ZI': 'Aigle Azur',
  'ZU': 'Helios Airways',
  'YM': 'Montenegro Airlines',
  '3K': 'Jetstar Asia Airways',
  '5V': 'Lviv Airlines',
  '6H': 'Israir',
  '5G': 'Skyservice Airlines',
  '3S': 'Air Antilles',
  '4B': 'Boutique Air',
  '4I': 'IHY Izmir Havayollari',
  '4F': 'Air City',
  '4R': 'Hamburg International',
  '9U': 'Air Moldova',
  '9X': 'New Axis Airways',
  '9T': 'Travelspan',
  '9P': 'Palau National Airlines',
  '9L': 'Colgan Air',
  '8W': 'Private Wings',
  '8P': 'Pacific Coastal Airlines',
  '8J': 'Jet4You',
  '8A': 'Atlas Blue',
  '7Y': 'Flying Carpet Air',
  '7Z': 'Halcyon Air',
  '/*S': 'SkyTeam Alliance',
  '/*O': 'Oneworld',
  'EI': 'Aer Lingus',
  'YB': 'Bora Jet',
  'U2': 'Easy jet',
  'EG': 'East Air',
  'FV': 'Rossiya',
  'Е5': 'Аllans АSR Samara',
  'YI': 'Air Sunshine',
  'Y4': 'Volaris',
  '6R': 'Alrosa Airlines',
  '4M': 'LATAM Airlines Argentina',
  'R2': 'Orenair',
  'D9': 'JSC Aeroflot Don',
  '3W': 'Wanair',
  'PC': 'Pegasus Airlines',
  'YQ': 'Polet',
  '4O': 'Interjet',
  '4V': 'Birdy Airlinesce',
  '5E': 'Nok Mini',
  '7P': 'Air Panama',
  '8E': 'Bering Air',
  '8F': 'STP Airways',
  '8N': 'Nordkalottflyg',
  '8Q': 'Onur Air',
  '8T': 'Air Tindi ',
  '8V': 'Wright Air',
  '9B': 'Accesrail INC.',
  '9C': 'Wimbi Dira Airways',
  '9J': 'Pacific Island Aviation',
  '9V': 'Avior Airlines',
  '9W': 'Jet Airways',
  'AA': 'American Airlines',
  'AO': 'Australian Airlines',
  'AV': 'Avianca',
  'GL': 'Air Greenland',
  'QZ': 'Indonesia AirAsia',
  'RH': 'Robin Hood Aviation',
  'RI': 'PT. Mandella Airlines',
  'RO': 'Tarom-Romanian Air',
  'RU': 'TCI Skyking LTD',
  'TC': 'Air Tanzania',
  'TJ': 'Tradewind Aviation',
  'UU': 'Air Austral',
  'JA': 'B&H Airlines',
  'OF': 'Air Finland',
  'OT': 'Aeropelican',
  'PB': 'Provincial Airlines',
  'PE': 'Peoples Vienna Line',
  'PK': 'Pakistan International Airline',
  'PR': 'Philippine Airlines',
  'PV': 'Saint Barth Commuter',
  'PW': 'Precisionair',
  'PX': 'Air Niugini',
  'E8': 'Alpi Eagles',
  'EJ': 'New England Airlines',
  'EM': 'Aero Benin',
  'F2': 'Safarilink',
  'FQ': 'Brindabella Airlines',
  'G0': 'Ghana International',
  'GA': 'Garuda',
  'VC': 'Air Australia',
  'DP': 'Pobeda',
  'QN': 'Air Armenia',
  'TQ': 'Tandem Aero',
  'V4': 'Vieques Air Link',
  'VF': 'Valuair',
  'VN': 'Vietnam Airlines',
  'VS': 'Virgin Atlantic',
  'WA': 'KLM Cityhopper',
  'WB': 'RwandAir',
  'WT': 'Wasaya Airways',
  'WY': 'Oman Air',
  'XV': 'MR Lines',
  'Y9': 'Kish Air',
  'YN': 'Air Creebec',
  'YV': 'Mesa Airlines',
  'Z3': 'PM Air ',
  'Z5': 'GMG Airlines',
  'Z7': 'Avia Traffic Company',
  'ZE': 'Eastar Jet',
  'ZH': 'Shenzhen Airlines',
  'ZV': 'Air Midwest',
  'ZZ': 'Airline Service',
  '2W': 'Welcome Air',
  'B5': 'East African Safari Air Express',
  'TM': 'LAM',
  'FB': 'Bulgaria Air',
  'X4': 'Vanair Limited',
  'U6': 'Ural Airlines',
  '5N': 'Smartavia (ex. Nordavia)',
  'O6': 'Oceanair',
  'EQ': 'TAME Linea Aerea del Ecuador',
  'MU': 'China Eastern',
  'VV': 'Viva Air Peru',
  'АД': 'Chukotavia State Aircompany',
  'Q2': 'Maldivian',
  'MW': 'Mokulele Airlines',
  'ЛП': 'Псковавиа',
  'LW': 'Pacific Wings',
  'GY': 'Sky Bishkek',
  '9K': 'Cape Air',
  'СП': 'Томск Авиа',
  'QF': 'Qantas',
  '6I': 'AeroSyncro',
  'H7': 'Taron Avia LLC',
  'QI': 'Cimber Sterling',
  '2I': 'Star Up',
  '9R': 'Satena',
  'QM': 'Monacair',
  'J4': 'Badr Airlines',
  'OS': 'Austrian',
  'YK': 'Avia Traffic Company',
  '2O': 'Island Air Service',
  '6T': 'Air Mandalay ',
  'XX': 'Test Airlines',
  'QV': 'Lao Aviation',
  'УТ': 'Турухан',
  'PI': 'Polar Airlines',
  'Z8': 'Amaszonas',
  'ДЖ': 'TEZ Jet',
  'H1': 'Hahn Air Systems',
  'ЯЛ': 'Yamal Airlines LLC',
  'ДТ': 'Air Management Group',
  '5C': 'Natureair',
  'RC': 'Atlantic Airways ',
  'DQ': 'Costal Air ',
  'DR': 'Air Link ',
  'DD': 'Nok Air',
  'DF': 'Aebal',
  'FE': 'Primaris Airlines',
  'FC': 'VivaColombia',
  'F8': 'Flair Airlines',
  'EW': 'Eurowings ',
  'EU': 'Ecuatoriana',
  'ES': 'DHL International',
  'F3': 'Flyadeal',
  'EH': 'Air Nippon',
  'EE': 'Regional Jet',
  'G6': 'Angkor Airways',
  'N4': 'Nordwind Airlines',
  'NG': 'Lauda Air Luftfahrt',
  'NB': 'Sterling',
  'NV': 'Air Central',
  'OJ': 'Overland Airways',
  'OW': 'Executive Airlines',
  'OO': 'Skywest Airlines ',
  'OR': 'Tui Airlines',
  'P2': 'AirKenya Express',
  'OQ': 'Chongqing Airlines',
  'PO': 'Polar Air Cargo',
  'PF': 'Primera Air Scandinavia',
  'HK': 'Yangon Airways',
  'HI': 'Papillon Airways',
  'HX': 'Hong Kong Airlines',
  'IH': 'Falcon Air',
  'J6': 'Larry\'s Flying Service',
  'J8': 'Berjaya Air',
  'ЭК': 'КрасАвиа',
  'JZ': 'Skyways ',
  'KC': 'Air Astana',
  'KP': 'ASKY',
  'LB': 'Bul Air',
  'LE': 'Lugansk Airlines',
  'VT': 'Air Tahiti',
  'W5': 'Mahan Air',
  'VU': 'Air Ivoire',
  'VE': 'Cai Second SPA',
  'V9': 'Bashkir Airlines',
  'UW': 'Universal Airlines',
  'UO': 'Hong Kong Express Airways',
  'UI': 'Eurocypria Airlines',
  'UJ': 'AlMasria Universal Airlines',
  'UG': 'Tunisair Express',
  'UC': 'Lan Chile Cargo',
  'U9': 'Tatarstan Airlines',
  'Y8': 'Yakutia',
  'XJ': 'Mesaba Aviation',
  'XO': 'LTE',
  'XM': 'Cai First',
  'XG': 'SunExpress Deutschland',
  'WX': 'City Jet',
  'X8': 'Icaro',
  'X7': 'Air Service',
  'WG': 'Sunwing Airlines',
  'WF': 'Wideroes Flyveselskap',
  'RF': 'Florida West International Airways',
  'RB': 'Syrian Arab Airlines',
  'RM': 'Regional Air',
  'QX': 'Horizon Air',
  'R4': 'Tulpar Avia',
  'R5': 'Malta Air Charter',
  'QQ': 'Alliance Airlines',
  'QR': 'Qatar Airways',
  'QY': 'European Air',
  'QE': 'Crossair Europe',
  'QC': 'Air Corridor',
  'QO': 'Origin Pacific Airways',
  'QJ': 'Latpass Airlines',
  'QK': 'Air Canada Jazz',
  'PQ': 'Panafrican',
  'PZ': 'TAM Mercosur',
  'TD': 'Atlantis European Airways',
  'TH': 'British Airways Citiexpress',
  'T8': 'STA Trans African Airlines',
  'SN': 'Brussels Airlines',
  'SM': 'Air Cairo',
  'SB': 'Air Calin',
  'ZC': 'Korongo Airlines',
  'ZN': 'Naysa',
  '3D': 'Denim Air',
  '3C': 'Corporate Express Airlines',
  '1X': 'Branson Air Express',
  '2L': 'Helvetic Airways',
  '8Z': 'Wizz Air Bulgaria',
  '8H': 'BH Air',
  '7W': 'Windrose Airlines',
  '/*A': 'Star Alliance',
  '3O': 'Air Arabia Maroc',
  '4N': 'Air North',
  'TS': 'Air Transat',
  'K2': 'Eurolot',
  'FY': 'Firefly',
  '4U': 'Germanwings',
  'JQ': 'Jetstar Airways',
  'LH': 'Lufthansa',
  'IG': 'Air Italy S.P.A.',
  'MM': 'Peach Airlines',
  'PD': 'Porter Airlines',
  'JW': 'Skippers',
  'SX': 'Skywork Airlines',
  'NK': 'Spirit Airlines',
  'XQ': 'SunExpress',
  'BY': 'Thomson Airways',
  'HV': 'Transavia',
  'TW': 'Tway Air',
  'VJ': 'VietJet Air',
  'VY': 'Vueling',
  'WS': 'WestJet',
  'W6': 'Wizz Air',
  'WW': 'WOW air',
  '7J': 'Tajikair',
  'NN': 'VIM Airlines',
  'G9': 'Air Arabia',
  'V8': 'Iliamna Air Taxi',
  'V5': 'Danube Wings',
  '7M': 'Trawel fly',
  '5R': 'Karthago Airlines',
  'UZ': 'Buraq Air',
  'CH': 'Bemidji Airlines',
  'IO': 'IrAero',
  'TK': 'Turkish Airlines',
  '2M': 'Moldavian Airlines',
  'ЖЯ': 'Almasria Universal Airlines',
  'PS': 'Ukraine International ',
  '2B': 'Albawings',
  'B2': 'Belavia',
  'HY': 'Uzbekistan Airways',
  'UT': 'UTair',
  'KD': 'Kalstar Aviation',
  'YO': 'Heli-Air Monaco',
  'M9': 'Motor Sich ',
  '7R': 'RusLine',
  'YC': 'Yamal Airlines',
  'НИ': 'RSUE KhabAvia',
  'ЮШ': 'ЗАО Авиакомпания Авиашельф',
  'LY': 'El Al ',
  'DV': 'SCAT',
  'J2': 'AZAL',
  'N3': 'Omskavia Airlines',
  '2GG': 'Cargoitalia',
  '2J': 'Air Burkina',
  '2K': 'Aerogal Aerolinas Galapagos',
  '3H': 'Air Inuit ',
  '3M': 'Silver Airways ',
  '4C': 'Aires',
  '4E': 'Tanana Air Service',
  'US': 'US Airways',
  '6P': 'Clubair Sixgo',
  '6Y': 'Smartlynx',
  '7C': 'Jeju Airlines',
  '7F': 'First Air',
  '7H': 'Ravn Alaska',
  '8B': 'Business Air Centre CO',
  'B8': 'Eritrean Airlines',
  'BR': 'EVA Airways ',
  'C8': 'NAC Air ',
  'CM': 'Copa Airlines',
  'CU': 'Cubana ',
  'CY': 'Cyprus Airways',
  'GC': 'Gambia International Airlines',
  'HH': 'Islandsflug ',
  'HM': 'Air Seychelles',
  'HW': 'North-Wright Air ',
  'I3': 'Ivoirienne de Transport',
  'I4': 'IFly',
  'IA': 'Iraqi Airways',
  'IR': 'Iran Air',
  'Q6': 'Skytrans',
  'Q7': 'Skybahamas',
  'QG': 'Qualiflyer Group',
  'QL': 'Laser Airlines',
  'RA': 'Nepal Airlines',
  'RQ': 'Kam Air',
  'RT': 'UVT aero',
  'RZ': 'Sansa Airlines',
  'S2': 'Jet Lite',
  'SA': 'South African Airways',
  'SD': 'Sudan Airways',
  'SF': 'Tassili Airlines',
  'SK': 'SAS ',
  'SQ': 'Singapore Airlines',
  'TA': 'Avianca El Salvador',
  'TL': 'Airnorth Regional',
  'TU': 'Tunis Air',
  'TX': 'Air Caraibes',
  'UE': 'Nasair',
  'UX': 'Air Europa',
  'V3': 'Carpatair',
  'IX': 'Air India Express',
  'J5': 'Alaska Seaplane',
  'J9': 'Jazeera Airways',
  'JN': 'Excel Airways',
  'JS': 'Air Koryo',
  'JT': 'Lion Air',
  'K5': 'Seaport Airlines',
  'K6': 'Cambodia Angkor Air',
  'KB': 'Druk Air',
  'KK': 'AtlasJet ',
  'KR': 'Comores Aviation',
  'KT': 'Katmai Air',
  'L9': 'Teamline Air Luftfahrt',
  'LA': 'Lan Airlines',
  'LS': 'Jet2.com',
  'MH': 'Malaysia Airline',
  'MI': 'SilkAir',
  'MO': 'CalmAir',
  'NT': 'Binter Canarias',
  'NU': 'Japan Trans Ocean Air',
  'O4': 'Orange2Fly',
  'OB': 'Boliviana de Aviacion',
  'OK': 'Czech Airlines',
  'P6': 'Pascan Aviation',
  'PG': 'Bangkok Airways',
  'PL': 'Southern Air Charter',
  'PY': 'Surinam Airways',
  'E4': 'Aero Asia',
  'EK': 'Emirates',
  'EP': 'Iran Assemam Airlines',
  'ET': 'Ethiopian',
  'EY': 'Etihad',
  'FJ': 'Fiji Airways',
  'FM': 'Shanghai Airlines',
  'FO': 'Felix Airways',
  'FP': 'Freedom Air',
  'G7': 'Gojet Airlines',
  '4D': 'Air Sinai',
  '5J': 'Cebu Pacific',
  '8M': 'Myanmar Airways',
  'V6': 'VIP S.A',
  'VA': 'Virgin Australia',
  'VB': 'Vivaaerobus',
  'VH': 'Viva Air Colombia',
  'VK': 'Level (Anisec Luftfahrt)',
  'VM': 'Macair Jet',
  'VW': 'Aeromar Airlines',
  'W4': 'LC Burse',
  'W9': 'Wizz Air UK',
  'WC': 'Islena Airlines',
  'WM': 'Windward Island Airways',
  'WP': 'Island Air',
  'XR': 'Corendon Airlines Europe',
  'Y5': 'Pace Airlines',
  'Z9': 'Bek Air',
  'AR': 'Aerolineas Argentinas',
  'D7': 'AirAsia',
  'SG': 'Spice Jet',
  'KE': 'Korean Air',
  'NR': 'Pamir Air',
  'P4': 'Aero Lineas Sosa',
  '6J': 'Solaseed Air',
  'JH': 'Nordeste-Linhas Aereas Regionals',
  '1Y': 'ВКШ Авиабизнес',
  'SW': 'Air Namibia',
  'ЛЖ': 'Kazan Air',
  'CO': 'Continental ',
  'TB': 'TUI fly Belgium',
  'JV': 'Bearskin Airlines',
  'I8': 'Ижавиа',
  'L6': 'Mauritania Airlines',
  'ТД': 'Таджик Эйр',
  'XY': 'Flynas',
  'EO': 'Pegas Fly',
  'O7': 'Оренбуржье',
  'СД': 'SKOL',
  '_1': 'Fake Carrier',
  '_4': 'FakeMyAirline',
  '_5': 'Fake Flyer',
  '_2': 'Test Airline',
  '_3': 'Test Carrier',
  'ПП': 'Utair',
  '6Ю': 'MC Aviaservice',
  'FA': 'FlySafair',
  'LM': 'Loganair',
  'OE': 'Laudamotion',
  'DI': 'Norwegian Air UK',
  'TO': 'Transavia France',
  'QD': 'JC International Airlines',
  'Э4': 'Fly&Bus',
  'UK': 'Vistara',
  'GK': 'Jetstar Japan',
  '4Z': 'Airlink',
  'HF': 'Air Cote d\'Ivoire',
  '00': 'Involatus',
  'I2': 'Iberia Express',
  'KN': 'China United Airlines',
  'ID': 'Batik Air',
  'WE': 'Thai Smile',
  'NI': 'Portugalia',
  'RS': 'Air Seoul',
  'HC': 'Air Senegal',
  'YU': 'EuroAtlantic Airways',
  '9I': 'Alliance Air',
  '8L': 'Lucky Air',
  'E2': 'Eurowings Europe',
  'UH': 'Atlasjet Ukraine',
  'NE': 'Nesma Airlines',
  'NP': 'Nile Air',
  'SR': 'Sundair',
  '1T': 'Bulgarian Air Charter',
  'E9': 'Evelop Airlines',
  '5I': 'Alsa Grupo SLU',
  '7G': 'StarFlyer',
  '2C': 'SNCF',
  '2A': 'Deutsche Bahn',
  'A1': 'APG Airlines',
  'RL': 'Royal Flight',
  'HP': 'Amapola Flyg',
  'F7': 'I Fly',
  '1L': 'CitizenPlane',
  'ZT': 'Titan Airways',
  'ED': 'AirExplore',
  'W7': 'Wings of Lebanon',
  'A2': 'Astra Airlines',
  'FT': 'FlyEgypt',
  '6A': 'Armenia Airways',
}

export { AIRLINE_CODE_TO_NAME_MAP }
