name: CI
on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: actions/setup-node@v2
        with: 
          cache: 'yarn'
          registry-url: 'registry.npmjs.org'
      # - run: yarn install
      # # - run: yarn build-storybook
      - run: yarn --frozen-lockfile
      - name: Run script file
        run: ./.github/scripts/build-prevesion.sh
        shell: bash
      # - run: yarn versionize
      # - run: echo "🎉  $VERSION "
      #   env: 
      #     VERSION: ${{ node -e "process.stdout.write(require('./package.json').version) }}